### ISSUE TITLE
L2 Tokenisation Task List

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#1009]
Here is the task list that defines what needs to completed as part of L2 Tokenisation. Each should form their own issues with corresponding PR. They are broadly grouped by their contribution to the end goal.

### Performance
- [ ] Migration to snarkjs backend #985 
- [ ] Enable rapidsnark as an option for server deployments.

### Flexibility
- [ ] Dynamic Commitment + Nullifier Arrays #986 
- [ ] Remove `TRANSACTION_TYPE` enum and replace `Key_Registry` to use a content-based hash #988
- [ ] Convert maximum transactions in `proposeBlock` to instead work on the `num_bytes` of the block + transactions.
- [ ] Metadata Array in On-chain Transaction Structure

### Usability
- [ ] Transfer/Withdraw that can use specific commitment hash
- [ ] Private Mint / Burn Zokrates circuit
