### ISSUE TITLE
PoS/Decentralization

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#1237]
- [x] Initial configuration PoS. #1248
- [x] Change proposer added to proposer so that proposer is added automatically. #1249
- [x] Estimate the cost the proposer has to charge in fees based in changeCurrentProposer gas cost or other related values. #1257
- [x] proposers claim fees periodically
- [x] proposers set a different minimum fee
- [x] challengers claim rewards periodically
- [ ] Other
