### ISSUE TITLE
Deploy beta testnet with Polygon block proposer and Polygon challenger for users (end of March)

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#533]
- [x] Build automatic, scalable and secure deployment of PNF
- [x] Deploy Goerli node for aligning with Polygon’s testnet environment 
- [x] Deploy PNF to staging 1 on Goerli testnet for internal dev
- [x] Ping pong wallet test the PNF deployment in staging 1
- [x] Deploy PNF to staging 2 on Goerli testnet for external users (Beta)
- [x] Create upgradeability playbook 
- [x] Perform upgradeability testing
