### ISSUE TITLE
Accumulation of themes for future epics 

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#544]
- [ ] Enable ERC721/ERC1155
- [ ] Reduce privacy costs further 
- [ ] Decentralisation of contract ownership
- [ ] PNF scanner (possibly)
