### ISSUE TITLE
Miscellaneous Browser Tasks

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#579]
### Fees + Payment
- [x] Switch networks (mainnet / polygon) when deposit / (send + withdraw) `Priority 0` - Ze
- [x] Collect fees in Matic when sending `Priority 0` - Ze
- [ ] Coinbase wallet support `Priority 1`
### Storage + Security
- [x] Encryption of secrets in the browser. `Priority 0`
- [ ] Export/Reimport IndexedDB button. `Priority 3`
- [x] Anonymity set `Priority 1`
### Usability and QoL
- [x] Decimal Handling in browser `Priority 0` #539 
- [x] Exchange rates and dollar values `Priority 1`
### Infrastructure
- [x] Stream and store circuits and proving keys `Priority 0` #469 
- [ ] Web workers for multi-threading. `Priority 1`
- [ ] Off load proof computations to web worker. `Priority 1`
- [ ] Rollback event handler. `Priority 0` #523 
- [ ] Integration in Polygon's website `Priority -1`
- [ ] Websocket keep-alive in wallet `Priority 0`

### Refactor
- [ ] Remove LOCAL_PROPOSER for wallet `Priority 4`

**Comment by IlyasRidhuan** [comment]
Closing, any open tasks will be migrated to V2
