### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#685]

**Comment by druiz0992** [comment]
Wallet should allow backup/restore commitments and support rollbacks

**Comment by druiz0992** [comment]
For this first phase, we will use existing wallet to exercise functionalities:

- [ ] Import/Export comitments (https://hackmd.io/XBgxdE5UTK2NUQ_vV4e5VA)
- [ ] Wallet needs to support rollback
- [ ] Publisher needs to support rollback

**Comment by luizoamorim** [comment]
@druiz0992 In terms of backend the functionality for rollbacks already exists?
