### ISSUE TITLE
Migrating to snarkjs backend.

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#985]
We currently use bellman for proof generation in ZoKrates-worker and zokrates-js. Since 0.8.2, ZoKrates can generate compiled circuits and witness that are compatible with the circom-ecosystem.

This should also significantly clean up the code in ZoKrates worker by removing the need for `spawn`-ing system processes.

Finally this opens the opportunity for us to utilise the impressively quick `rapidsnark` prover. Early benchmarks for `rapidsnark` show it is 30x faster than bellman.

### Task list (all wallet updates will replace zokrates-js calls)
- [ ] Replace `zokrates setup` + `mpc` process with `snarkjs` phase 1 & 2 setups.
- [x] Update `zokrates compile` to also generate the relevant `circom.r1cs` output.
- [x] Update  `ZoKrates compute-witness` to also generate `circom.wtns` output.
- [x] Replace proof generation with `snarkjs groth16 prove`.
- [x] Update the serialisation of verification key that are stored in `Key Registry.sol`

**Comment by druiz0992** [comment]
Not sure if related, or should go under a different issue, but for the client we should allow to use rapid snark on  multiple servers

**Comment by IlyasRidhuan** [comment]
Yeah that is a good point, we could either have it as a toggle as part of the `config` (e.g.  `PROVING_CONFIG = ${rapidsnark_url} or zokrates-worker`.

 So either 
1. You run it locally (containerised) with ZoKrates-worker (or I  guess circom-worker) and `snarkjs` is used.
2. You provide it a url that handles proof generation (this could then be an AWS cluster where rapidsnark is deployed)

rapidsnark seems to be perfect for big machines with multi-cores, so we should be fine with snarkjs local
